name: CI Build UAT

on:
  push:
    branches-ignore:
      - 'master'
      - 'dev'
jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test
        run: ./mvnw verify
      
      