name: CI Deploy PROD

on:
  push:
    branches:
      - 'master'
      - 'feature-monitoring'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
  
      - name: Unit Tests
        run: ./mvnw verify

      - name: Rename the artifact
        run: cp target/devops-0.0.1-SNAPSHOT.jar devops-${{ github.sha}}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@v3
        with:
          name: devops_artifact
          path: devops-${{ github.sha}}.jar

  push_to_docker_hub_registry:
    name: Push Docker image to docker hub
    runs-on: ubuntu-latest
    needs: build-test
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      
      - name: Log in to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: 13luscher/up-palermo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          #tags: ${{ github.repository }}:${{ github.sha }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  fake-deploy:
      runs-on: ubuntu-latest
      needs: push_to_docker_hub_registry
      steps:
        - name: Get artifact
          uses: actions/download-artifact@v3
          with:
            name: devops_artifact

        - name: Fake deploy
          run: ls devops-*.jar